version: 2.1

jobs:
 build:
  docker:
   - image: holochain/holonix:latest.develop
  steps:
   - checkout
   - run: nix-shell --run ./test.sh

 deploy-crates:
  docker:
   - image: holochain/holonix:latest
  steps:
   - checkout
   - run:
      no_output_timeout: 20m
      command: nix-shell --run "hn-release-hook-publish-crates-io 'holochain_wasmer_common holochain_wasmer_host holochain_wasmer_guest'"

workflows:
 version: 2.1
 tests:
  jobs:
   - build

 deploy:
  jobs:
   - deploy-crates:
      filters:
       branches:
        ignore: /.*/
       tags:
        only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
