[package]
name = "holochain_wasmer_common"
description = "commons for both host and guest"
license = "GPL-3.0-only"
version = "0.0.39"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[dependencies]
holochain_serialized_bytes = "=0.0.41"
serde = "=1.0.104"
thiserror = "1.0.10"
