[package]
name = "holochain_wasmer_common"
description = "commons for both host and guest"
license = "GPL-3.0-only"
version = "0.0.31"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[dependencies]
holochain_serialized_bytes = { git = "https://github.com/holochain/holochain-serialization", branch = "2020-06-06-serde-bytes" }
serde = "=1.0.104"
thiserror = "1.0.10"
