[package]
name = "guest"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "guest"
crate-type = [ "cdylib", "rlib" ]
path = "src/guest.rs"

[dependencies]
wee_alloc = "=0.4.5"
common = { path = "../common" }
