[package]
name = "holochain_wasmer_host"
description = "wasm host code"
license = "GPL-3.0-only"
version = "0.0.67"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[dependencies]
wasmer = "=1.0.2"
wasmer-compiler-singlepass = "=1.0.2"
holochain_wasmer_common = { version = "=0.0.67", path = "../common" }
holochain_serialized_bytes = "=0.0.50"
serde = "=1.0.123"
tracing = "0.1"
parking_lot = "0.11.1"

[lib]
name = "holochain_wasmer_host"
crate-type = [ "cdylib", "rlib" ]
path = "src/host.rs"
