[package]
name = "holochain_wasmer_host"
description = "wasm host code"
license = "GPL-3.0-only"
version = "0.0.66"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[dependencies]
wasmer-runtime-core = "=0.16.2"
wasmer-runtime = "=0.16.2"
holochain_wasmer_common = { version = "=0.0.66", path = "../common" }
lazy_static = "1.4.0"
holochain_serialized_bytes = "=0.0.48"
serde = "=1.0.104"
tracing = "0.1"

[lib]
name = "holochain_wasmer_host"
crate-type = [ "cdylib", "rlib" ]
path = "src/host.rs"
