[package]
name = "holochain_wasmer_host"
description = "wasm host code"
license = "GPL-3.0-only"
version = "0.0.67"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[dependencies]
wasmer = { git = "https://github.com/wasmerio/wasmer", rev = "99f42b0c01ab04953bc5457d5708ac812d4bbddf" }
holochain_wasmer_common = { version = "=0.0.67", path = "../common" }
holochain_serialized_bytes = "=0.0.50"
serde = "=1.0.123"
tracing = "0.1"
parking_lot = "0.11.1"
once_cell = "1.5.2"
rand = "0.8.3"

[lib]
name = "holochain_wasmer_host"
crate-type = [ "cdylib", "rlib" ]
path = "src/host.rs"
