[package]
name = "host"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[dependencies]
wasmer-runtime = "=0.13.1"
byte-slice-cast = "=0.3.5"
common = { path = "../common" }

[lib]
name = "host"
crate-type = [ "cdylib", "rlib" ]
path = "src/host.rs"
