[package]
name = "holochain_wasmer_guest"
description = "wasm guest code"
license = "GPL-3.0-only"
version = "0.0.66"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[workspace]

[lib]
name = "holochain_wasmer_guest"
crate-type = [ "cdylib", "rlib" ]
path = "src/guest.rs"

[dependencies]
holochain_wasmer_common = { version = "=0.0.66", path = "../common" }
serde = "=1.0.123"
tracing = "0.1"

[dependencies.holochain_serialized_bytes]
version = "=0.0.50"
features = []
