[package]
name = "holochain_wasmer_guest"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "holochain_wasmer_guest"
crate-type = [ "cdylib", "rlib" ]
path = "src/guest.rs"

[dependencies]
holochain_wasmer_common = { path = "../common" }
