name: run tests

on: [ push, pull_request ]

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: nix-actions/cache-install@v1.0.6
     with:
       key: nix-${{ hashFiles('default.nix') }}-${{ hashFiles('config.nix') }}
       nix_file: 'default.nix'
   # - uses: cachix/install-nix-action@v12
   #   with:
   #     nix_path: nixpkgs=channel:nixos-unstable
   # - run: nix-shell --run ./test.sh
   - run: ./test.sh
